In [3]:
from funkisar import *
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(torch.cuda.is_available())

torch.set_default_tensor_type('torch.cuda.FloatTensor')

False


In [2]:
training_set = ['ES2002', 'ES2005', 'ES2006', 'ES2007', 'ES2008', 'ES2009', 'ES2010', 'ES2012', 'ES2013', 'ES2015', 'ES2016', 'IS1000', 'IS1001', 'IS1002', 'IS1003', 'IS1004', 'IS1005', 'IS1006', 'IS1007', 'TS3005', 'TS3008', 'TS3009', 'TS3010', 'TS3011', 'TS3012']
validation_set=['IS1000', 'ES2002']
for thing in validation_set:
    training_set.remove(thing)

In [3]:
#bst=get_modelFromSet(['ES2002a', 'ES2002b'])
bst=get_modelFromSet(training_set)
#validation_set=['TS3012']

score=get_scoreFromset(bst, validation_set)
print(score)

#baseline=0.319
#with features=0.329

#0.416



bst device:  cuda:0


bert device:  cuda:0


Encoding: 100%|██████████| 89/89 [10:31<00:00,  7.10s/it]


Fitting Data
bert device:  cuda:0


Encoding: 100%|██████████| 8/8 [01:03<00:00,  8.00s/it]
C:\Users\maxrl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\xgboost\core.py:160: UserWarning: [16:17:41] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\common\error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)


0.46661031276415893


[0 1 1 0 0 1 0 0 1 0]
[0 0 0 1 0 1 0 0 0 1]


array([ 0.04081633,  0.04081633,  0.04081633, -0.24489796,  0.04081633,
       -0.24489796,  0.04081633,  0.04081633,  0.04081633, -0.24489796])